### PR TITLE
feat: cext-1505: Initiate workspace

### PR DESCRIPTION
**Pull request by dani97**
## Description

This feature allows user to create a workspace for local development.
The user can create workspace with git, package manager as yarn / npm. 

## Related Issue

https://jira.corp.adobe.com/browse/CEXT-1505

## How Has This Been Tested?

This new command is testing by running this cli commands
aio api-mesh init  test-project-p ../template-projects/cmw -g -m yarn - This will create a test project at the given path with yarn as package manager
-p path | default is .
-m packageManager | default is npm | supported npm,yarn
-g git | default false | true, flase

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by revanth0212** [comment]
I am yet to review the code but please make sure to merge these changes to `epic/local-dev` branch instead.

**Review by revanth0212 — CHANGES_REQUESTED** [review]
Hey @dani97 

I havent reviewed the code yet but here are some of my suggestions for a better user experience:

1. The CLI seems to be complaining about creating mesh in an existing folder. I dont think that is needed, use the name of the project they give, create a folder with that name in the current location and setup the local env. In the current example, ask them if they want to create in `/Users/annavara/Documents/projects/graphql/aio-cli-plugin-api-mesh/meshFiles/myMesh` and if they say yes, continue:
image
2. CLI doesnt seem to be asking for package managers (npm / yarn). It is automatically using `npm`.
3. CLI doesnt seems to be setting up git before it can create a folder. That is not accurate.

**Comment by dani97** [comment]
> Hey @dani97
> 
> I havent reviewed the code yet but here are some of my suggestions for a better user experience:
> 
> 1. The CLI seems to be complaining about creating mesh in an existing folder. I dont think that is needed, use the name of the project they give, create a folder with that name in the current location and setup the local env. In the current example, ask them if they want to create in `/Users/annavara/Documents/projects/graphql/aio-cli-plugin-api-mesh/meshFiles/myMesh` and if they say yes, continue:
>    image
> 2. CLI doesnt seem to be asking for package managers (npm / yarn). It is automatically using `npm`.
> 3. CLI doesnt seems to be setting up git before it can create a folder. That is not accurate.

@revanth0212 For issues 2 and 3 I have created them as flags but I can change it to prompts as well.
I took reference from this comment in the ticket `aio api-mesh init --path ./mesh_projects/test_mesh --git N --package-manager yarn `

**Comment by revanth0212** [comment]
> > Hey @dani97
> > I havent reviewed the code yet but here are some of my suggestions for a better user experience:
> > 
> > 1. The CLI seems to be complaining about creating mesh in an existing folder. I dont think that is needed, use the name of the project they give, create a folder with that name in the current location and setup the local env. In the current example, ask them if they want to create in `/Users/annavara/Documents/projects/graphql/aio-cli-plugin-api-mesh/meshFiles/myMesh` and if they say yes, continue:
> >    image
> > 2. CLI doesnt seem to be asking for package managers (npm / yarn). It is automatically using `npm`.
> > 3. CLI doesnt seems to be setting up git before it can create a folder. That is not accurate.
> 
> @revanth0212 For issues 2 and 3 I have created them as flags but I can change it to prompts as well. I took reference from this comment in the ticket `aio api-mesh init --path ./mesh_projects/test_mesh --git N --package-manager yarn `

It should ask questions about where to create, git and pkg manager but if they are already provided as flags it should avoid those questions and use the flag values instead. The same has been mentioned in the ticket. Please check it out

**Review by revanth0212 — APPROVED** [review]

**Pull request merged**
